"""added csv to tables

Revision ID: 2311a2c97bae
Revises: bfc86e6e5832
Create Date: 2024-10-15 13:19:39.619542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2311a2c97bae'
down_revision = 'bfc86e6e5832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.Text(), nullable=False))
        batch_op.drop_column('titles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titles', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
