"""changing field names

Revision ID: bb16cacca873
Revises: 2311a2c97bae
Create Date: 2024-10-15 13:20:47.505242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb16cacca873'
down_revision = '2311a2c97bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titles', sa.Text(), nullable=False))
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('titles')

    # ### end Alembic commands ###
